---
#
# Ansible managed
#
repository:
  description: Install and configure revealmd on your system.
  homepage: https://buluma.github.io/
  topics: revealmd, presentation, html, markdown, nodejs, git, npm, slides, ansible, molecule, tox, playbook, hacktoberfest
